### ISSUE TITLE
Make Gson customizable

### ISSUE THREAD

**Issue by TjeuKayim** [TjeuKayim/socket-interface#1]
One should be able to use GsonBuilder to customize the JSON encoding.

Possible solutions:
- Add Gson as a parameter to MessageSender.create and the constructor of MessageReceiver
- The interface can implement a method like `getGson()`

**Comment by ghost** [comment]
Another solution would be to delegate the encoding and decoding of a message to an interface. This would make the code even more generic.

**Comment by ghost** [comment]
```java
interface MessageEncoder {
  String encode(Message message)
  Message decode(String)
}

class Message {
  String interfaceName;
  String methodName;
  Object[] arguments;
}
```

**Comment by ghost** [comment]
Or just change the string-consumer in a message-consumer

**Comment by TjeuKayim** [comment]
It's implemented
